# Creating a vector

In [1]:
import numpy as np

In [8]:
row_vector = np.array([1, 2, 3, 4, 5]) #creating a row vector
row_vector, type(row_vector), row_vector.shape, row_vector.ndim

(array([1, 2, 3, 4, 5]), numpy.ndarray, (5,), 1)

In [9]:
col_vector = np.array([ 
    [1],
    [2],
    [3],
    [4],
    [5]
]) #creating a column vector
col_vector, type(col_vector), col_vector.shape, col_vector.ndim

(array([[1],
        [2],
        [3],
        [4],
        [5]]),
 numpy.ndarray,
 (5, 1),
 2)

**Numpy's main data structure is the multidimensional array. A vector is just a one dimensional array in Numpy.**

# Creating a matrix

In [10]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix, type(matrix), matrix.shape, matrix.ndim

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray,
 (3, 3),
 2)

# Creating a sparse matrix

In [11]:
#very few non-zero values
from scipy import sparse

In [12]:
matrix = np.array([
    [0, 0, 0, 0, 1],
    [1, 0, 0, 0, 0],
    [0, 0, 1, 1, 0],
    [0, 0, 1, 0, 0],
    [1, 1, 0, 0, 1]
])

In [22]:
matrix_sparse = sparse.csr_matrix(matrix) #creating a compressed sparse row (csr) matrix

In [23]:
matrix_sparse

<5x5 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

In [24]:
print(matrix_sparse)

  (0, 4)	1
  (1, 0)	1
  (2, 2)	1
  (2, 3)	1
  (3, 2)	1
  (4, 0)	1
  (4, 1)	1
  (4, 4)	1


In [25]:
matrix_sparse[0, 2], matrix_sparse[2, 3]

(0, 1)

**If you have a huge amout of data but most of the elements are zeros, you can use csr matrix. Sparse matrices only store non-zero elements and assumes all the other elements are zero leads to computational savings.**

In [27]:
small_matrix = np.array([
    [0, 9],
    [3, 0]
])
large_matrix = np.array([
    [0, 9, 0, 0, 0, 0, 0, 0, 0, 0],
    [3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
])

In [28]:
small_sparse = sparse.csr_matrix(small_matrix)
large_sparse = sparse.csr_matrix(large_matrix)

In [29]:
print(small_sparse)

  (0, 1)	9
  (1, 0)	3


In [30]:
print(large_sparse)

  (0, 1)	9
  (1, 0)	3


# Selecting elements

In [31]:
nums = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [32]:
nums[0]

array([1, 2, 3])

In [37]:
nums[1, 1]

5

In [38]:
nums[1][1]

5

In [47]:
nums, nums[::]

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [52]:
nums[:2], nums[0:2]

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [56]:
nums[2:], nums[2:3], nums[2:1000000]

(array([[7, 8, 9]]), array([[7, 8, 9]]), array([[7, 8, 9]]))

In [58]:
nums[-1], nums[2]

(array([7, 8, 9]), array([7, 8, 9]))

In [60]:
nums[-1, -1], nums[2, 2]

(9, 9)

In [62]:
nums[0, -1], nums[0, 2]

(3, 3)

In [68]:
#first two rows and last two column
nums[:2, 1:]

array([[2, 3],
       [5, 6]])

In [72]:
#only the middle column
nums[:, 1]

array([2, 5, 8])

# Describing a matrix

In [75]:
nums = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

In [76]:
nums.shape

(3, 5)

In [78]:
nums.size #number of elements in the matrix

15

In [79]:
nums.ndim

2

# Applying operations to elements

In [80]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [81]:
nums_plus_hundred = lambda nums: nums + 100

In [84]:
vectorized_add_hundred = np.vectorize(nums_plus_hundred)

In [85]:
vectorized_add_hundred(nums)

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115]])

In [86]:
#but it's simple
nums_plus_hundred = nums + 100
nums_plus_hundred

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115]])

In [87]:
Out[85] == Out[86]

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

**the simpler one (nums + 100) is called broadcasting.**

# Finding the maximum and minimum values

In [90]:
np.max(nums), np.min(nums)

(15, 1)

In [91]:
np.max(nums[0]), np.min(nums[0])

(5, 1)

In [93]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [97]:
np.max(nums[:, 2]), np.min(nums[:, 2])

(13, 3)

In [101]:
#find max in each column
np.max(nums, axis = 0)

array([11, 12, 13, 14, 15])

In [102]:
#find max in each row
np.max(nums, axis = 1)

array([ 5, 10, 15])

# Calculating the avg, var and SD

In [104]:
nums.mean(), np.mean(nums)

(8.0, 8.0)

In [105]:
nums.var(), np.var(nums)

(18.666666666666668, 18.666666666666668)

In [106]:
nums.std(), np.std(nums)

(4.320493798938574, 4.320493798938574)

In [107]:
nums[:, 3].mean(), np.mean(nums[:, 3])

(9.0, 9.0)

In [110]:
np.mean(nums, axis = 0)

array([ 6.,  7.,  8.,  9., 10.])

# Reshaping arrays

In [112]:
nums.shape

(3, 5)

In [120]:
nums.reshape(15, 1), nums.reshape(15, 1).shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]]),
 (15, 1))

In [122]:
nums.size == nums.reshape(15, 1).size

True

In [125]:
nums.reshape(1, -1) #-1 means as many as needed, (1, -1) is 1 row and as many columns needed

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [126]:
nums.reshape(-1, 1) #(-1, 1) is 1 column and as many rows as needed

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [131]:
nums.reshape(1, -1), nums.reshape(1, -1).ndim

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]), 2)

In [132]:
nums.reshape(15), nums.reshape(15).ndim

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]), 1)

# Transposing a vector or matrix

In [133]:
nums, nums.shape

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]),
 (3, 5))

In [134]:
nums.T, nums.T.shape

(array([[ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14],
        [ 5, 10, 15]]),
 (5, 3))

In [136]:
row_vector = np.array([1, 2, 3])
col_vector = np.array([
    [1],
    [2],
    [3]
])

In [142]:
row_vector.T, row_vector.shape, row_vector.T.shape, row_vector.T.ndim

(array([1, 2, 3]), (3,), (3,), 1)

In [144]:
col_vector.T, col_vector.shape, col_vector.T.shape, col_vector.T.ndim

(array([[1, 2, 3]]), (3, 1), (1, 3), 2)

In [146]:
row_vector_twodim = np.array([
    [1, 2, 3]
])
row_vector_twodim

array([[1, 2, 3]])

In [148]:
row_vector_twodim.T, row_vector_twodim.shape, row_vector_twodim.T.shape

(array([[1],
        [2],
        [3]]),
 (1, 3),
 (3, 1))

# Flattening a matrix

In [149]:
nums.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [151]:
nums.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [153]:
nums.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

# Finding the rank of a matrix

In [155]:
np.linalg.matrix_rank(nums)

2

# Calculating the determinant

In [157]:
nums = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.det(nums)

-9.51619735392994e-16

# Getting the diagonal of a matrix

In [158]:
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
nums.diagonal()

array([1, 5, 9])

In [170]:
nums.diagonal(offset = 1) #diagonal one above the main diagonal

array([2, 6])

In [171]:
nums.diagonal(offset = -1) #diagonal one below the main diagonal

array([4, 8])

In [172]:
nums.diagonal(offset = 2)

array([3])

In [173]:
nums.diagonal(offset = -2)

array([7])

# Calculating the trace of a matrix

In [174]:
nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [176]:
nums.trace() #sum of the diagonal elements or trace

15

In [177]:
sum(nums.diagonal())

15

# Finding eigenvalues and eigenvectors

In [178]:
eigenvalues, eigenvectors = np.linalg.eig(nums)

In [179]:
eigenvalues, eigenvectors

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

# Calculating dot products

In [181]:
numbers = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [2, 3, 9]
])

In [182]:
np.dot(nums, numbers)

array([[ 9, 12, 30],
       [21, 27, 63],
       [33, 42, 96]])

In [183]:
nums @ numbers

array([[ 9, 12, 30],
       [21, 27, 63],
       [33, 42, 96]])

# Adding and subtracting matrices

In [184]:
np.add(nums, numbers)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 18]])

In [185]:
np.subtract(nums, numbers)

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 0]])

In [186]:
nums + numbers

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 9, 11, 18]])

In [187]:
nums - numbers

array([[0, 1, 2],
       [3, 4, 5],
       [5, 5, 0]])

# Multiplying matrices

In [188]:
np.dot(nums, numbers), nums @ numbers

(array([[ 9, 12, 30],
        [21, 27, 63],
        [33, 42, 96]]),
 array([[ 9, 12, 30],
        [21, 27, 63],
        [33, 42, 96]]))

In [191]:
#elementwise multiplication
nums * numbers

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [14, 24, 81]])

# Inverting a matrix

In [211]:
nums = np.array([
    [1, 3, 9],
    [3, 5, 2],
    [1, 2, 9]
])
np.linalg.inv(nums)

array([[-1.64000000e+00,  3.60000000e-01,  1.56000000e+00],
       [ 1.00000000e+00, -6.52256027e-18, -1.00000000e+00],
       [-4.00000000e-02, -4.00000000e-02,  1.60000000e-01]])

In [218]:
np.round(nums @ np.linalg.inv(nums), 1)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

# Generating random values

In [219]:
np.random.seed(9)

In [221]:
np.random.random(3)

array([0.16677635, 0.87855909, 0.95096403])

In [223]:
np.random.randint(0, 10, 50)

array([3, 6, 7, 9, 0, 8, 1, 8, 1, 6, 6, 2, 8, 4, 5, 3, 4, 0, 8, 0, 4, 5,
       4, 8, 3, 8, 4, 8, 0, 1, 2, 3, 7, 7, 2, 0, 4, 6, 2, 2, 2, 3, 9, 2,
       1, 3, 0, 1, 0, 2])

In [224]:
#draw 5 numbers from a normal distribution with mean 0.0 and std of 1.0
np.random.normal(0.0, 1.0, 5)

array([ 0.19362181, -0.61399333, -0.35045614,  0.88993001, -0.77907708])

In [225]:
#draw 5 numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 5)

array([ 2.23405665,  1.41302122, -5.38501464, -1.27925192,  0.99241706])

In [226]:
#draw 5 numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 5)

array([1.31975528, 1.54886864, 1.03677212, 1.81723195, 1.51794704])